export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const GET_USER = "GET_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const PUSH_USER = "PUSH_USER";
export const REMOVE_USER = "REMOVE_USER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_CHANNEL = "SET_CHANNEL";
export const SOCKET_CONNECTION = "SOCKET_CONNECTION";
export const PUBLIC_CHANNELS = "PUBLIC_CHANNELS";
export const SET_SEARCHED_CHANNELS = "SET_SEARCHED_CHANNELS";
export const SET_SEARCHING = "SET_SEARCHING";
export const REMOVE_SEARCHED_CHANNELS = "REMOVE_SEARCHED_CHANNELS";
export const SET_CHANNELS = "SET_CHANNELS";
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const SET_RECENT_MESSAGE = 'SET_RECENT_MESSAGE';


